name: build-and-deploy-ftp

on:
  push:
    branches: [ "main" ]

concurrency:
  group: "deploy-ftp"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: FTP Deploy (dist)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./dist/    # ← IMPORTANTE: termina con /
          server-dir: /looptrack_react/
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
